---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Hello beautiful!"
subtitle: "App dashboard"
logo: false
#icon: "fas fa-skull-crossbones" #Optional icon

header: true

# Optional theme customization
theme: sui
colors:
  light:
    highlight-primary: transparent
    highlight-secondary: transparent
    highlight-hover: "#4a4a4a"
    text-subtitle: "#424242"
  dark:
    background: "#2B2C56"
    highlight-primary: transparent
    highlight-secondary: transparent
    highlight-hover: "#200b35"
    text-subtitle: "#6375e8"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links: []

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media Playback"
    items:
      - name: "General Jellyfin"
        icon: "fas fa-tv"
        subtitle: "TV, Movies, Music and Anime Playback"
        url: "https://jellyfin.oriondev.tech:8096"
      - name: "Adult Jellyfin"
        icon: "fas fa-video"
        subtitle: "Adult content"
        url: "http://xxx.oriondev.tech:8096" 
  - name: "Media Management"
    items:
      - name: "Sonarr"
        icon: "fas fa-tv"
        subtitle: "TV & Anime Management"
        url: "https://sonarr.oriondev.tech:8989"
      - name: "Radarr"
        icon: "fas fa-film"
        subtitle: "Movie Management"
        url: "https://radarr.oriondev.tech:7878"
      - name: "Lidarr"
        icon: "fas fa-music"
        subtitle: "Music Library Management"
        url: "https://lidarr.oriondev.tech:8686"
  - name: "Orion Stuff"
    items:
      - name: "Email"
        icon: "fas fa-envelope-open-text"      
        subtitle: "Side Business Email"
        url: "https://mail.zoho.com"
      - name: "Odoo ERP"
        icon: "fas fa-file-invoice-dollar"
        subtitle: "Billing and Invoicing"
        url: "http://odoo.twiz.lab:8069"
  - name: "Hosting"
    items:
      - name: "PVE1"
        icon: "fas fa-server"
        subtitle: "Primary Hypervisor"
        url: "https://pve1.oriondev.tech:8006"
      - name: "Portainer"
        icon: "fab fa-docker"
        subtitle: "Docker Controller"
        url: "http://docker.twiz.lab:9000"
    